/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FashionDesignSubmission {
  'status' : SubmissionStatus,
  'title' : string,
  'description' : string,
  'isPaid' : boolean,
  'email' : string,
  'timestamp' : Time,
  'image' : ExternalBlob,
  'artistName' : string,
}
export type SubmissionStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'selected' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetAllSubmissions' : ActorMethod<[], Array<FashionDesignSubmission>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllSubmissions' : ActorMethod<[], Array<FashionDesignSubmission>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSubmissionCount' : ActorMethod<[], bigint>,
  'getSubmissionsByStatus' : ActorMethod<
    [SubmissionStatus],
    Array<FashionDesignSubmission>
  >,
  'getUnpaidSelectedDesigns' : ActorMethod<[], Array<FashionDesignSubmission>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markDesignAsPaid' : ActorMethod<[string], undefined>,
  'submitDesign' : ActorMethod<[FashionDesignSubmission], string>,
  'updateSubmissionStatus' : ActorMethod<[string, SubmissionStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];