/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SubmissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'selected' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FashionDesignSubmission = IDL.Record({
  'status' : SubmissionStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isPaid' : IDL.Bool,
  'email' : IDL.Text,
  'timestamp' : Time,
  'image' : ExternalBlob,
  'artistName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetAllSubmissions' : IDL.Func(
      [],
      [IDL.Vec(FashionDesignSubmission)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSubmissions' : IDL.Func(
      [],
      [IDL.Vec(FashionDesignSubmission)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSubmissionsByStatus' : IDL.Func(
      [SubmissionStatus],
      [IDL.Vec(FashionDesignSubmission)],
      ['query'],
    ),
  'getUnpaidSelectedDesigns' : IDL.Func(
      [],
      [IDL.Vec(FashionDesignSubmission)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markDesignAsPaid' : IDL.Func([IDL.Text], [], []),
  'submitDesign' : IDL.Func([FashionDesignSubmission], [IDL.Text], []),
  'updateSubmissionStatus' : IDL.Func([IDL.Text, SubmissionStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SubmissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'selected' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FashionDesignSubmission = IDL.Record({
    'status' : SubmissionStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isPaid' : IDL.Bool,
    'email' : IDL.Text,
    'timestamp' : Time,
    'image' : ExternalBlob,
    'artistName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetAllSubmissions' : IDL.Func(
        [],
        [IDL.Vec(FashionDesignSubmission)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSubmissions' : IDL.Func(
        [],
        [IDL.Vec(FashionDesignSubmission)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSubmissionsByStatus' : IDL.Func(
        [SubmissionStatus],
        [IDL.Vec(FashionDesignSubmission)],
        ['query'],
      ),
    'getUnpaidSelectedDesigns' : IDL.Func(
        [],
        [IDL.Vec(FashionDesignSubmission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markDesignAsPaid' : IDL.Func([IDL.Text], [], []),
    'submitDesign' : IDL.Func([FashionDesignSubmission], [IDL.Text], []),
    'updateSubmissionStatus' : IDL.Func([IDL.Text, SubmissionStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };